- name: Include necessary variables
  ansible.builtin.include_vars: ../vars/main.yml

- name: Update apt cache and install latest wireguard
  ansible.builtin.apt:
    name: wireguard
    update_cache: true

- name: Update sysctl to allow ipv4 port forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true

- name: Create Wireguard keys directory
  ansible.builtin.file:
    path: /etc/wireguard/keys
    state: directory

- name: Create private Wireguard key and store it into correct file
  ansible.builtin.command: "wg genkey"
  register: wireguard_server_privatekey

- name: Create public Wireguard key and store it into correct file
  ansible.builtin.command: "wg pubkey"
  args:
    stdin: "{{ wireguard_server_privatekey.stdout }}"
  register: wireguard_server_pubkey

- name: Creating wg0 config file
  ansible.builtin.template:
    src: ../templates/wg0.j2
    dest: /etc/wireguard/wg0.conf
    mode: "0644"

- name: Bring wg0 interface up
  ansible.builtin.command: "wg-quick up wg0"

- name: Print Public key of server
  ansible.builtin.debug:
    msg: "{{ wireguard_server_pubkey.stdout }}"
